personservice:
  datasource:
    hr:
      url: jdbc:postgresql://localhost:5432/hr?currentSchema=person
      username: postgres
      password: postgres
      configuration:
        pool-name:  person pool
        type: com.zaxxer.hikari.HikariDataSource
        connectionTimeout: 1000
  liquibase:
    hr:
      change-log: classpath:/changelog/master.xml
      default-schema: person

spring:
  application:
    name: personservice
#  boot:
#    admin:
#      client:
#        url: http://localhost:8082

management:
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always
      cache:
        time-to-live: 10s
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
#        include: '*'
        include: health, loggers, metrics, caches

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: 8081
  servlet:
    contextPath: /${spring.application.name}