personservice:
  datasource:
    hr:
      url: jdbc:postgresql://localhost:5432/hr?currentSchema=person
      username: postgres
      password: postgres
  liquibase:
    hr:
      change-log: classpath:/changelog/master.xml
      default-schema: person

spring:
  application:
    name: personservice

management:
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always
      cache:
        time-to-live: 10s
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, loggers, metrics, caches

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: 8081
  servlet:
    contextPath: /${spring.application.name}