version: '3.8'
services:
  postgress:
    build:
      dockerfile: ./postgres_hr.dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hr
    ports:
      - '5432:5432'
